### ISSUE TITLE
How do I use the `duration` and `gap` options?

### ISSUE THREAD

**Issue by JacobDB** [andreruffert/snackbar#2]
The documentation isn't very clear on how to set the duration and gap.

**Comment by andreruffert** [comment]
I've updated the [README.md](/andreruffert/snackbar/blob/master/README.md#usage) + the [example](/andreruffert/snackbar/blob/master/example/index.html#L19-L20). Hope this helps :)

**Comment by JacobDB** [comment]
Ah, that makes sense, thanks!
